#pragma once
#include <tiny_gui/config.h>
#include <tiny_gui/bitmap.h>
#include <tiny_gui/color.h>
#include <tiny_gui/display.h>
#include <tiny_gui/dynamic_array.h>
#include <tiny_gui/font.h>
#include <tiny_gui/graphics.h>
#include <tiny_gui/widgets.h>